# Generated by Django 4.2.3 on 2023-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='description')),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('auction', models.BooleanField(default=False, verbose_name='auction')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date of publication')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
        ),
    ]
