# Generated by Django 4.2.3 on 2023-08-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='advertisements',
        ),
    ]
